package com.daily.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_article
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   文章名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * Database Column Remarks:
     *   关联商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.shop_id
     *
     * @mbggenerated
     */
    private String shopId;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   发布人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   发布人名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.create_user_name
     *
     * @mbggenerated
     */
    private String createUserName;

    /**
     * Database Column Remarks:
     *   文章来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.src
     *
     * @mbggenerated
     */
    private String src;

    /**
     * Database Column Remarks:
     *   文章图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.article_pictrue
     *
     * @mbggenerated
     */
    private String articlePictrue;

    /**
     * Database Column Remarks:
     *   文章标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.id
     *
     * @return the value of tbl_article.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.id
     *
     * @param id the value for tbl_article.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.article_title
     *
     * @return the value of tbl_article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.article_title
     *
     * @param articleTitle the value for tbl_article.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.shop_id
     *
     * @return the value of tbl_article.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.shop_id
     *
     * @param shopId the value for tbl_article.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.create_time
     *
     * @return the value of tbl_article.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.create_time
     *
     * @param createTime the value for tbl_article.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.create_user_id
     *
     * @return the value of tbl_article.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.create_user_id
     *
     * @param createUserId the value for tbl_article.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.create_user_name
     *
     * @return the value of tbl_article.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.create_user_name
     *
     * @param createUserName the value for tbl_article.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.src
     *
     * @return the value of tbl_article.src
     *
     * @mbggenerated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.src
     *
     * @param src the value for tbl_article.src
     *
     * @mbggenerated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.article_pictrue
     *
     * @return the value of tbl_article.article_pictrue
     *
     * @mbggenerated
     */
    public String getArticlePictrue() {
        return articlePictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.article_pictrue
     *
     * @param articlePictrue the value for tbl_article.article_pictrue
     *
     * @mbggenerated
     */
    public void setArticlePictrue(String articlePictrue) {
        this.articlePictrue = articlePictrue == null ? null : articlePictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article.type
     *
     * @return the value of tbl_article.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article.type
     *
     * @param type the value for tbl_article.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}