package com.daily.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_shop
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * Database Column Remarks:
     *   原价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * Database Column Remarks:
     *   现价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.price_now
     *
     * @mbggenerated
     */
    private String priceNow;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.shop_pictrue
     *
     * @mbggenerated
     */
    private String shopPictrue;

    /**
     * Database Column Remarks:
     *   发布日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.Num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.delete_status
     *
     * @mbggenerated
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   上传用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.create_user_name
     *
     * @mbggenerated
     */
    private String createUserName;

    /**
     * Database Column Remarks:
     *   购买连接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.news_src
     *
     * @mbggenerated
     */
    private String newsSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.conclum1
     *
     * @mbggenerated
     */
    private String conclum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shop.conclum2
     *
     * @mbggenerated
     */
    private String conclum2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.id
     *
     * @return the value of tbl_shop.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.id
     *
     * @param id the value for tbl_shop.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.shop_name
     *
     * @return the value of tbl_shop.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.shop_name
     *
     * @param shopName the value for tbl_shop.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.price
     *
     * @return the value of tbl_shop.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.price
     *
     * @param price the value for tbl_shop.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.price_now
     *
     * @return the value of tbl_shop.price_now
     *
     * @mbggenerated
     */
    public String getPriceNow() {
        return priceNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.price_now
     *
     * @param priceNow the value for tbl_shop.price_now
     *
     * @mbggenerated
     */
    public void setPriceNow(String priceNow) {
        this.priceNow = priceNow == null ? null : priceNow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.shop_pictrue
     *
     * @return the value of tbl_shop.shop_pictrue
     *
     * @mbggenerated
     */
    public String getShopPictrue() {
        return shopPictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.shop_pictrue
     *
     * @param shopPictrue the value for tbl_shop.shop_pictrue
     *
     * @mbggenerated
     */
    public void setShopPictrue(String shopPictrue) {
        this.shopPictrue = shopPictrue == null ? null : shopPictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.create_time
     *
     * @return the value of tbl_shop.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.create_time
     *
     * @param createTime the value for tbl_shop.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.Num
     *
     * @return the value of tbl_shop.Num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.Num
     *
     * @param num the value for tbl_shop.Num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.number
     *
     * @return the value of tbl_shop.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.number
     *
     * @param number the value for tbl_shop.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.delete_status
     *
     * @return the value of tbl_shop.delete_status
     *
     * @mbggenerated
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.delete_status
     *
     * @param deleteStatus the value for tbl_shop.delete_status
     *
     * @mbggenerated
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.create_user_id
     *
     * @return the value of tbl_shop.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.create_user_id
     *
     * @param createUserId the value for tbl_shop.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.create_user_name
     *
     * @return the value of tbl_shop.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.create_user_name
     *
     * @param createUserName the value for tbl_shop.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.news_src
     *
     * @return the value of tbl_shop.news_src
     *
     * @mbggenerated
     */
    public String getNewsSrc() {
        return newsSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.news_src
     *
     * @param newsSrc the value for tbl_shop.news_src
     *
     * @mbggenerated
     */
    public void setNewsSrc(String newsSrc) {
        this.newsSrc = newsSrc == null ? null : newsSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.conclum1
     *
     * @return the value of tbl_shop.conclum1
     *
     * @mbggenerated
     */
    public String getConclum1() {
        return conclum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.conclum1
     *
     * @param conclum1 the value for tbl_shop.conclum1
     *
     * @mbggenerated
     */
    public void setConclum1(String conclum1) {
        this.conclum1 = conclum1 == null ? null : conclum1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shop.conclum2
     *
     * @return the value of tbl_shop.conclum2
     *
     * @mbggenerated
     */
    public String getConclum2() {
        return conclum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shop.conclum2
     *
     * @param conclum2 the value for tbl_shop.conclum2
     *
     * @mbggenerated
     */
    public void setConclum2(String conclum2) {
        this.conclum2 = conclum2 == null ? null : conclum2.trim();
    }
}