package com.daily.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public ShopExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNowIsNull() {
            addCriterion("price_now is null");
            return (Criteria) this;
        }

        public Criteria andPriceNowIsNotNull() {
            addCriterion("price_now is not null");
            return (Criteria) this;
        }

        public Criteria andPriceNowEqualTo(String value) {
            addCriterion("price_now =", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowNotEqualTo(String value) {
            addCriterion("price_now <>", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowGreaterThan(String value) {
            addCriterion("price_now >", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowGreaterThanOrEqualTo(String value) {
            addCriterion("price_now >=", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowLessThan(String value) {
            addCriterion("price_now <", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowLessThanOrEqualTo(String value) {
            addCriterion("price_now <=", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowLike(String value) {
            addCriterion("price_now like", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowNotLike(String value) {
            addCriterion("price_now not like", value, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowIn(List<String> values) {
            addCriterion("price_now in", values, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowNotIn(List<String> values) {
            addCriterion("price_now not in", values, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowBetween(String value1, String value2) {
            addCriterion("price_now between", value1, value2, "priceNow");
            return (Criteria) this;
        }

        public Criteria andPriceNowNotBetween(String value1, String value2) {
            addCriterion("price_now not between", value1, value2, "priceNow");
            return (Criteria) this;
        }

        public Criteria andShopPictrueIsNull() {
            addCriterion("shop_pictrue is null");
            return (Criteria) this;
        }

        public Criteria andShopPictrueIsNotNull() {
            addCriterion("shop_pictrue is not null");
            return (Criteria) this;
        }

        public Criteria andShopPictrueEqualTo(String value) {
            addCriterion("shop_pictrue =", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueNotEqualTo(String value) {
            addCriterion("shop_pictrue <>", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueGreaterThan(String value) {
            addCriterion("shop_pictrue >", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueGreaterThanOrEqualTo(String value) {
            addCriterion("shop_pictrue >=", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueLessThan(String value) {
            addCriterion("shop_pictrue <", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueLessThanOrEqualTo(String value) {
            addCriterion("shop_pictrue <=", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueLike(String value) {
            addCriterion("shop_pictrue like", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueNotLike(String value) {
            addCriterion("shop_pictrue not like", value, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueIn(List<String> values) {
            addCriterion("shop_pictrue in", values, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueNotIn(List<String> values) {
            addCriterion("shop_pictrue not in", values, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueBetween(String value1, String value2) {
            addCriterion("shop_pictrue between", value1, value2, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andShopPictrueNotBetween(String value1, String value2) {
            addCriterion("shop_pictrue not between", value1, value2, "shopPictrue");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNull() {
            addCriterion("delete_status is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNotNull() {
            addCriterion("delete_status is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusEqualTo(String value) {
            addCriterion("delete_status =", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotEqualTo(String value) {
            addCriterion("delete_status <>", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThan(String value) {
            addCriterion("delete_status >", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThanOrEqualTo(String value) {
            addCriterion("delete_status >=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThan(String value) {
            addCriterion("delete_status <", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThanOrEqualTo(String value) {
            addCriterion("delete_status <=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLike(String value) {
            addCriterion("delete_status like", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotLike(String value) {
            addCriterion("delete_status not like", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIn(List<String> values) {
            addCriterion("delete_status in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotIn(List<String> values) {
            addCriterion("delete_status not in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusBetween(String value1, String value2) {
            addCriterion("delete_status between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotBetween(String value1, String value2) {
            addCriterion("delete_status not between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("create_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("create_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("create_user_name =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("create_user_name <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("create_user_name >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_name >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("create_user_name <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("create_user_name <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("create_user_name like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("create_user_name not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("create_user_name in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("create_user_name not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("create_user_name between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("create_user_name not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andNewsSrcIsNull() {
            addCriterion("news_src is null");
            return (Criteria) this;
        }

        public Criteria andNewsSrcIsNotNull() {
            addCriterion("news_src is not null");
            return (Criteria) this;
        }

        public Criteria andNewsSrcEqualTo(String value) {
            addCriterion("news_src =", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcNotEqualTo(String value) {
            addCriterion("news_src <>", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcGreaterThan(String value) {
            addCriterion("news_src >", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcGreaterThanOrEqualTo(String value) {
            addCriterion("news_src >=", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcLessThan(String value) {
            addCriterion("news_src <", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcLessThanOrEqualTo(String value) {
            addCriterion("news_src <=", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcLike(String value) {
            addCriterion("news_src like", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcNotLike(String value) {
            addCriterion("news_src not like", value, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcIn(List<String> values) {
            addCriterion("news_src in", values, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcNotIn(List<String> values) {
            addCriterion("news_src not in", values, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcBetween(String value1, String value2) {
            addCriterion("news_src between", value1, value2, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andNewsSrcNotBetween(String value1, String value2) {
            addCriterion("news_src not between", value1, value2, "newsSrc");
            return (Criteria) this;
        }

        public Criteria andConclum1IsNull() {
            addCriterion("conclum1 is null");
            return (Criteria) this;
        }

        public Criteria andConclum1IsNotNull() {
            addCriterion("conclum1 is not null");
            return (Criteria) this;
        }

        public Criteria andConclum1EqualTo(String value) {
            addCriterion("conclum1 =", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1NotEqualTo(String value) {
            addCriterion("conclum1 <>", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1GreaterThan(String value) {
            addCriterion("conclum1 >", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1GreaterThanOrEqualTo(String value) {
            addCriterion("conclum1 >=", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1LessThan(String value) {
            addCriterion("conclum1 <", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1LessThanOrEqualTo(String value) {
            addCriterion("conclum1 <=", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1Like(String value) {
            addCriterion("conclum1 like", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1NotLike(String value) {
            addCriterion("conclum1 not like", value, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1In(List<String> values) {
            addCriterion("conclum1 in", values, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1NotIn(List<String> values) {
            addCriterion("conclum1 not in", values, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1Between(String value1, String value2) {
            addCriterion("conclum1 between", value1, value2, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum1NotBetween(String value1, String value2) {
            addCriterion("conclum1 not between", value1, value2, "conclum1");
            return (Criteria) this;
        }

        public Criteria andConclum2IsNull() {
            addCriterion("conclum2 is null");
            return (Criteria) this;
        }

        public Criteria andConclum2IsNotNull() {
            addCriterion("conclum2 is not null");
            return (Criteria) this;
        }

        public Criteria andConclum2EqualTo(String value) {
            addCriterion("conclum2 =", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2NotEqualTo(String value) {
            addCriterion("conclum2 <>", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2GreaterThan(String value) {
            addCriterion("conclum2 >", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2GreaterThanOrEqualTo(String value) {
            addCriterion("conclum2 >=", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2LessThan(String value) {
            addCriterion("conclum2 <", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2LessThanOrEqualTo(String value) {
            addCriterion("conclum2 <=", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2Like(String value) {
            addCriterion("conclum2 like", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2NotLike(String value) {
            addCriterion("conclum2 not like", value, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2In(List<String> values) {
            addCriterion("conclum2 in", values, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2NotIn(List<String> values) {
            addCriterion("conclum2 not in", values, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2Between(String value1, String value2) {
            addCriterion("conclum2 between", value1, value2, "conclum2");
            return (Criteria) this;
        }

        public Criteria andConclum2NotBetween(String value1, String value2) {
            addCriterion("conclum2 not between", value1, value2, "conclum2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_shop
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_shop
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}